////////////////////////////////////////////////////////////////////////////
// $Id: Deint_Diag.h,v 1.2 2003-10-31 17:19:37 adcockj Exp $
/////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2003 John Adcock.  All rights reserved.
// This software was based on sample code generated by the 
// DMO project wizard.  That code is (c) Microsoft Corporation
/////////////////////////////////////////////////////////////////////////////
//
// This file is free software; you can redistribute it and/or modify it
// under the terms of the GNU Library General Public License as published by
// the Free Software Foundation; either version 2 of the License, or (at your
// option) any later version.
//
// This software is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Library General Public License for more details
//
/////////////////////////////////////////////////////////////////////////////
// CVS Log
//
// $Log: not supported by cvs2svn $
// Revision 1.1  2003/05/21 13:41:12  adcockj
// Added new deinterlace methods
//
/////////////////////////////////////////////////////////////////////////////

#pragma once

#include "..\..\DMO_Lib\DMO_Lib.h"
#include "..\..\DMO_Lib\CDeintDMO.h"
#include "resource.h"


class ATL_NO_VTABLE DECLSPEC_UUID("CAAD7294-8B6C-11d7-B851-0002A5623377") CDeint_Diag : 
	public CDeintDMO,
    public IAmFreeSoftwareLicensed,
	public CComCoClass<CDeint_Diag, &__uuidof(CDeint_Diag)>
{
public:
    CDeint_Diag();	// Constructor
    ~CDeint_Diag();	// Destructor

    DECLARE_REGISTRY( CDeint_Diag, _T("DMO.Deint_Diag"), _T("DMO.Deint_Diag.1"), IDS_DESCRIPTION, THREADFLAGS_BOTH);

BEGIN_COM_MAP(CDeint_Diag)
	COM_INTERFACE_ENTRY(IAmFreeSoftwareLicensed)
    COM_INTERFACE_ENTRY_CHAIN(CDeintDMO)
END_COM_MAP()


public:
    STDMETHODIMP STDMETHODCALLTYPE GetClassID(CLSID *pClsid);

// IAmFreeSoftwareLicensed
public:
	STDMETHOD(get_Name)(BSTR* Name);
	STDMETHOD(get_License)(eFreeLicense* License);
	STDMETHOD(get_Authors)(BSTR* Authors);

// IDeinterlace
public:
    STDMETHOD(Process)(IInterlacedBufferStack* Stack, IMediaBuffer* pOutBuffer);

protected:
	HRESULT SetParamInternal(DWORD dwParamIndex, MP_DATA value, bool fSkipPasssingToParamManager);

private:
};

