////////////////////////////////////////////////////////////////////////////
// $Id: Deint_Bob.h,v 1.2 2003-05-20 16:50:58 adcockj Exp $
/////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2003 John Adcock.  All rights reserved.
// This software was based on sample code generated by the 
// DMO project wizard.  That code is (c) Microsoft Corporation
/////////////////////////////////////////////////////////////////////////////
//
// This file is free software; you can redistribute it and/or modify it
// under the terms of the GNU Library General Public License as published by
// the Free Software Foundation; either version 2 of the License, or (at your
// option) any later version.
//
// This software is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Library General Public License for more details
//
/////////////////////////////////////////////////////////////////////////////
// CVS Log
//
// $Log: not supported by cvs2svn $
// Revision 1.1  2003/05/16 16:19:12  adcockj
// Added new files into DMO framework
//
/////////////////////////////////////////////////////////////////////////////

#pragma once

#include "..\..\DMO_Lib\DMO_Lib.h"
#include "..\..\DMO_Lib\CDeintDMO.h"
#include "resource.h"


class ATL_NO_VTABLE DECLSPEC_UUID("13F75833-8615-11d7-B84E-0002A5623377") CDeint_Bob : 
	public CDeintDMO,
    public IAmFreeSoftwareLicensed,
	public CComCoClass<CDeint_Bob, &__uuidof(CDeint_Bob)>
{
public:
    CDeint_Bob();	// Constructor
    ~CDeint_Bob();	// Destructor

    DECLARE_REGISTRY( CDeint_Bob, _T("DMO.Deint_Bob"), _T("DMO.Deint_Bob.1"), IDS_DESCRIPTION, THREADFLAGS_BOTH);

BEGIN_COM_MAP(CDeint_Bob)
	COM_INTERFACE_ENTRY(IAmFreeSoftwareLicensed)
    COM_INTERFACE_ENTRY_CHAIN(CDeintDMO)
END_COM_MAP()


public:
    STDMETHODIMP STDMETHODCALLTYPE GetClassID(CLSID *pClsid);

// IAmFreeSoftwareLicensed
public:
	STDMETHOD(get_Name)(BSTR* Name);
	STDMETHOD(get_License)(eFreeLicense* License);
	STDMETHOD(get_Authors)(BSTR* Authors);

protected:
	HRESULT SetParamInternal(DWORD dwParamIndex, MP_DATA value, bool fSkipPasssingToParamManager);

    virtual void DoDeinterlacingMethod(DMO_OUTPUT_DATA_BUFFER *pOutputBuffer);

private:
};

