#!/bin/sh
./configure --extra-cflags="-fno-common -D_WIN32_WINNT=0x0600" --enable-memalign-hack --enable-shared --disable-static --disable-debug --disable-encoders --disable-muxers --disable-devices --enable-gpl
make clean
make version.h
make
mkdir ../Debug
mkdir ../Release
./dscalercopyfile.sh libavcodec/avcodec-52 Debug Release
./dscalercopyfile.sh libavformat/avformat-52 Debug Release
./dscalercopyfile.sh libavutil/avutil-50 Debug Release
./dscalercopyfile.sh libswscale/swscale-0 Debug Release
