#!/bin/sh
./configure --extra-cflags="-mno-cygwin -mms-bitfields" --extra-ldflags="-Wl,--add-stdcall-alias,--enable-auto-import" --enable-memalign-hack --target-os=mingw32 --enable-shared --disable-static --disable-debug --disable-encoders --disable-muxers --disable-devices --enable-gpl
make clean
make
mkdir ../Debug
mkdir ../Release
./dscalercopyfile.sh libavcodec/avcodec-52 Debug Release
./dscalercopyfile.sh libavformat/avformat-52 Debug Release
./dscalercopyfile.sh libavutil/avutil-50 Debug Release
./dscalercopyfile.sh libswscale/swscale-0 Debug Release
