#!/bin/sh
./configure --enable-cross-compile --cross-prefix=x86_64-pc-mingw32- --extra-cflags="-D__MINGW32_MAJOR_VERSION=4" --arch=x86_64 --enable-w32threads --disable-static --enable-shared --disable-debug --disable-network --disable-avisynth --disable-demuxer=vfwcap --disable-encoders --disable-muxers --disable-devices --enable-gpl
make clean
make
mkdir ../Debug64
mkdir ../Release64
./dscalercopyfile.sh libavcodec/avcodec-52 Debug64 Release64
./dscalercopyfile.sh libavformat/avformat-52 Debug64 Release64
./dscalercopyfile.sh libavutil/avutil-50 Debug64 Release64
./dscalercopyfile.sh libswscale/swscale-0 Debug64 Release64
